luggage_av:
  controller_manager:
    ros__parameters:
      update_rate: 100  # Hz

      diff_drive_controller:
        type: diff_drive_controller/DiffDriveController

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

