<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

    <xacro:include filename="params.xacro" />

    <material name="black">
        <color rgba="0 0 0 1"/>
    </material>

    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>

    <xacro:property name="my_x_origin" value="${chassis_length/2}" />
    <xacro:property name="my_y_origin" value="${-chassis_width/2}" />
    <xacro:property name="my_z_origin" value="${chassis_height - drive_wheel_radius + chassis_Z_offset}" />

    <xacro:property name="my_x_length" value="0.05" />
    <xacro:property name="my_y_length" value="0.05" />
    <xacro:property name="my_z_length" value="0.293" />

    <joint name="lidar_mount_joint" type="fixed">
        <parent link="base_link"/>
        <child link="lidar_mount_link"/>
        <origin xyz = "${my_x_origin-my_x_length/2 + chassis_X_offset} ${my_y_origin+my_y_length/2} ${my_z_origin + my_z_length/2}"/>
    </joint>

    <link name="lidar_mount_link">
        <visual>
            <origin xyz = "0 0 0"/>
            <geometry>
                <box size="${my_x_length} ${my_y_length} ${my_z_length}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz = "0 0 0"/>
            <geometry>
                <box size="${my_x_length} ${my_y_length} ${my_z_length}"/>
            </geometry>
            <material name="black"/>
        </collision>
        <xacro:inertial_box mass="0.1" x="${my_x_length}" y="${my_y_length}" z="${my_z_length}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>

    <joint name="laser_joint" type="fixed">
        <parent link="lidar_mount_link"/>
        <child link="laser"/>
        <origin xyz = "0 0 0.167"/> <!--half the height of the mount + half the height of the lidar itself (0.293+0.04)/2-->
    </joint>

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0.167" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- <joint name="laser_joint" type="fixed">
        <parent link="chassis"/>
        <child link="laser_frame"/>
        <origin xyz="0.122 0 0.212" rpy="0 0 0"/>
    </joint>

    <link name="laser_frame">
        <visual>
            <geometry>
                <box radius="0.05" length="0.04"/>
            </geometry>
            <material name="black"/>
        </visual>
        <visual>
            <origin xyz="${chassis_length/2 - 0.1} ${-chassis_width/2} -0.05"/>
            <geometry>
                <cylinder radius="0.01" length="0.1"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.05" length="0.04"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.05">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link> -->



    <gazebo reference="laser">
        <material>Gazebo/blue</material>

        <sensor name="laser" type="gpu_lidar">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>false</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14</min_angle>
                        <max_angle>3.14</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <gz_frame_id>luggage_av/laser</gz_frame_id>
        </sensor>
    </gazebo>

</robot>